# Generated by Django 5.2 on 2025-12-05 16:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=100)),
                ('donor_email', models.EmailField(db_index=True, max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(100)])),
                ('reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('verified', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('donation_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='post.donationpost')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'verified'], name='paystack_do_created_995ca3_idx'), models.Index(fields=['donation_post', 'verified'], name='paystack_do_donatio_58c925_idx')],
            },
        ),
    ]
